#!/bin/sh

##  code_version.sh:
##  Write the SVN version of the code and the compiler name to a Fortran source file
##  MvdS, 24/07/2010


if [[ ${#} -ne 2 ]]; then
    
    echo -e "\n  syntax:   code_version.sh  <CMake base dir>  <Fortran compiler name>\n"

else
    
    BASEDIR=${1}                                # Base directory of the package
    COMPILER=${2}                               # Compiler name
    F90FILE=${BASEDIR}"/src/code_version.f90"   # Fortran-90 output file
    
    
    echo "Generating ${F90FILE}"
    
    echo "!> \file code_version.f90  Source file automatically generated by Makefile to report the code version used." > ${F90FILE}
    echo "subroutine print_code_version" >> ${F90FILE}
    echo "  use basic, only: stdOut" >> ${F90FILE}
    echo "  implicit none" >> ${F90FILE}
    echo "  character :: svn_revision*(99) = '"`svnversion`"'" >> ${F90FILE}
    echo "  character :: compile_date*(99) = '"`date`"'" >> ${F90FILE}
    echo "  character :: compiler*(99) = '"${COMPILER}"'" >> ${F90FILE}
    echo "  write(stdOut,'(A)')'svn revision: '//trim(svn_revision)//', compiled on '//trim(compile_date)//' with '//trim(compiler)//'.'" >> ${F90FILE}
    echo 'end subroutine print_code_version' >> ${F90FILE}
    
    touch -d "1 Jan 2001" ${F90FILE}            # Make the file look old
    
fi


