#!/bin/bash
# This script checks for the presence of analysemcmc.dat
# If it doesn't exist, it gets a fresh copy
# If it does exist it does a diff and, if different, asks whether to keep the old version, use the new version or interactively merge both versions into a new file


#The location of the default analysemcmc.dat on your system
SRCFILE=${HOME}"/work/GW/programs/MCMC/mcmc_plot/trunk/analysemcmc.dat"  

DESTFILE="analysemcmc.dat"  #Name of the analysemcmc init file
BCKPFILE="analysemcmc.old"  #Name for a backup copy of this file

DIFFCMD="colordiff -N" #Use this command to diff two files
MRGCMD="sdiff -s --diff-program=diff" #Use this command to merge two files

#Default argument for cp is -i; if command-line arguments are given, pass them to cp (e.g. -f always overwrites)
CPOPT="-i"
if [ $# -gt 0 ]
then
    CPOPT="$@"
fi



echo
DESTLEN=0
if [ -a $DESTFILE ]
then
    DESTLEN=$(wc -l $DESTFILE | awk '{ print $1}') #Number of lines in the destination file
    SRCLEN=$(wc -l $SRCFILE | awk '{ print $1}')   #Number of lines in the source file
    DELTA=$(($SRCLEN - $DESTLEN))
    if [ $DELTA -gt 0 ]
    then
	echo "  The current file has $DELTA lines less than the default file"
    elif [ $DELTA -lt 0 ]
    then
	DELTA=$(($DELTA*(-1)))
	echo "  The current file has $DELTA lines more than the default file"
    elif [ $DELTA -eq 0 ]
    then
	echo "  The current file has the same number of lines as the default file"
    fi
else
    echo "  No $DESTFILE was found in the current directory"
fi



echo
if [ -a $DESTFILE ]
then
    if diff -q $DESTFILE $SRCFILE
    then 
	echo "  Your version of $DESTFILE is uptodate"
    else
	$DIFFCMD "$DESTFILE" "$SRCFILE" |less --no-init --QUIT-AT-EOF
	#cp $CPOPT $SRCFILE .
	echo -ne "\n   Would you like to (K)eep the old file, (U)se the new file or (M)erge the two files interactively?  "
	read ans1
	if [[ "$ans1" == "m" || "$ans1" == "M" ]] #Merge
	then
	    echo -e "\n\n   Below, you see lines of the two versions side by side. The old (current) version is on the left, the new (default) version is on the right.\n   Press 'l' or 'r' to use the left or right version, 'q' to quit and '?' for help:"
	    mv -f $DESTFILE $BCKPFILE
	    $MRGCMD $BCKPFILE $SRCFILE -o $DESTFILE
	    echo "  The merged file is stored as $DESTFILE, the old file was saved as $BCKPFILE"
	elif [[ "$ans1" == "u" || "$ans1" == "U" ]] #Copy
	then 
	    cp $SRCFILE .
	    echo "  I replaced your copy of $DESTFILE with a fresh one"
	else 
	    echo "  I kept the old file" #Keep
	fi
    fi

else
    cp $CPOPT $SRCFILE .
    echo "  I brought in a fresh $DESTFILE"
fi

echo

